security:
    
    encoders:
         Anpe\Bundle\UserBundle\Entity\User:
             algorithm:        sha512
             encode_as_base64: true
             iterations:       10

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH ]
    
    
    providers:
        main:
            entity: { class: Anpe\Bundle\UserBundle\Entity\User, property: email }
                
    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern:   ^/
            anonymous: true
            provider:  main
            form_login:
                login_path: login
                check_path: login_check
                always_use_default_target_path: true
                default_target_path: /
            logout:
                path:   logout
                target: /
            security: true
            remember_me:
                key:        %secret% 

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }

